// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAKazz3ugVetudey5MzM-VRKj24pQ7fik',
    appId: '1:557208520275:web:9721c4b703d5ed7f2be8a6',
    messagingSenderId: '557208520275',
    projectId: 'fragrance-app-128b1',
    authDomain: 'fragrance-app-128b1.firebaseapp.com',
    storageBucket: 'fragrance-app-128b1.appspot.com',
    measurementId: 'G-38PBY6HBTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJjfSu3td4loSmeTnLwGB8_tfPdhbMycs',
    appId: '1:557208520275:android:4f633d6ad956c09f2be8a6',
    messagingSenderId: '557208520275',
    projectId: 'fragrance-app-128b1',
    storageBucket: 'fragrance-app-128b1.appspot.com',
  );
}
